### ISSUE TITLE
Create DB Lookup table

### ISSUE THREAD

**Issue by juyeonlee221** [bellepoque7/whereisplanb#2]
### 관련 이슈
- DB Lookup table 생성

### 내용
- 농축수산물 품목 및 등급 코드표 파일 활용하여 각 시트별 DB Lookup table 생성

### 기한
- 2022/12/18

**Comment by juyeonlee221** [comment]
@bellepoque7 아래 링크에 있는 파일(농축수산물 품목 및 등급 코드표) 활용하면 될까요?
https://www.kamis.or.kr/customer/reference/openapi_list.do?action=detail&boardno=2

**Comment by ggplab** [comment]
> @bellepoque7 아래 링크에 있는 파일(농축수산물 품목 및 등급 코드표) 활용하면 될까요?
> https://www.kamis.or.kr/customer/reference/openapi_list.do?action=detail&boardno=2

네~
